---
version: '2'
services:
  mz800emu:
    build: .
    devices: 
        - "/dev/dri"
        - "/dev/snd"
    environment:
        - "DISPLAY"
    network_mode: "host"
    volumes:
        - "$HOME/.Xauthority:/root/.Xauthority:rw" 
        - "$PWD:/root/host"

